[package]
name = "calc-creator"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = "thin"
strip = true


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.3"
